# Config server
server.port=8080
server.servlet.context-path=/instahub
spring.application.name=instahub_api

# Config connect to db local
spring.datasource.url=jdbc:mysql://localhost:3306/instahub_db
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.signerKey=${JWT_SIGNER_KEY}
jwt.valid-duration=3600
jwt.refreshable-duration=604800

app.frontend-url=http://localhost:3000
